alter table HOMEBOOKKEEPINGCUBA_EXPENSES alter column ACCOUNT rename to ACCOUNT__U67116 ^
drop index IDX_HOMEBOOKKEEPINGCUBA_EXPENSES_ON_ACCOUNT ;
alter table HOMEBOOKKEEPINGCUBA_EXPENSES add column ACCOUNT integer ;
