alter table HOMEBOOKKEEPINGCUBA_INCOME alter column NAMECATEGORY rename to NAMECATEGORY__U26302 ^
alter table HOMEBOOKKEEPINGCUBA_INCOME alter column NAMECATEGORY__U26302 set null ;
alter table HOMEBOOKKEEPINGCUBA_INCOME add column NAME_CATEGORY_ID integer ;
