alter table HOMEBOOKKEEPINGCUBA_INCOME alter column ACCOUNT rename to ACCOUNT__U75063 ^
drop index IDX_HOMEBOOKKEEPINGCUBA_INCOME_ON_ACCOUNT ;
alter table HOMEBOOKKEEPINGCUBA_INCOME add column ACCOUNT integer ;
