alter table HOMEBOOKKEEPINGCUBA_TRANSFER alter column ACCOUN_TO_ID rename to ACCOUN_TO_ID__U34678 ^
drop index IDX_HOMEBOOKKEEPINGCUBA_TRANSFER_ON_ACCOUN_TO ;
alter table HOMEBOOKKEEPINGCUBA_TRANSFER alter column ACCOUNT_FROM_ID rename to ACCOUNT_FROM_ID__U29218 ^
drop index IDX_HOMEBOOKKEEPINGCUBA_TRANSFER_ON_ACCOUNT_FROM ;
alter table HOMEBOOKKEEPINGCUBA_TRANSFER add column ACCOUNT_FROM_ID integer ;
alter table HOMEBOOKKEEPINGCUBA_TRANSFER add column ACCOUN_TO_ID integer ;
